hide_download: true
hide_download_original: null
leftnav:
- identifier: bf4843a1-13a6-b83c-d04f-ad7400ed4b33
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 5c97646d-7a9e-b098-74c2-87c4bf4aecb9
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 209e999a-e580-2544-3af6-a169562185e7
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 799c0026-3644-ac2d-53ad-f53bcbec3908
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 84445a7b-8bcd-842a-d1ca-7ec822c4d48e
  name: Projects
  pageRef: /pages/projects
  weight: 50
- identifier: 9202d855-369a-4332-98af-be8f45df2f23
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 60
